import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { authOptions } from "@/lib/auth";
import { getServerSession } from "next-auth";
import SelfSessionProvider from "@/app/SelfSessionProvider";
import { Suspense } from "react";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const BasicHeader = dynamic(() => import('@/components/headers/BasicHeader'))


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions);


  return (

    <html lang="en">
      <body className={inter.className}>
        <SelfSessionProvider session={session}>

          {/* <Toaster /> //TODO: TOASTER SERVICE PROVIDER using Sonner */}
          <Suspense>
            <BasicHeader />
          </Suspense>
          {children}
        </SelfSessionProvider>
      </body>
    </html>
  );
}
