name: Update VPS Repo with Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ closed ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build Application
        working-directory: main-app
        run: npm run build

      - name: Connect to VPS (SSH)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: 'root'
          password: ${{ secrets.VPS_PASSWORD }}

      - name: Upload Build (if successful build)
        run: |
          if [ $? -eq 0 ]; then
            cd /home/ubuntu/ris/PublishWhere
            git pull origin main
            pm2 restart all
          fi


# ALL ENVIROMENT VARIABLES ARE FAKE, REAL ONES ARE ON SERVER, IF NO ON GITHUB NOR ON SERVER, APP WILL BE UPLOADED TO VPS
env:
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  NODE_ENV: "production"
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
  BUCKET_ACCESS_KEY: ${{ secrets.BUCKET_ACCESS_KEY }}
  BUCKET_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_SECRET_ACCESS_KEY }}
  URL_SOCIAL_MEDIA_CONNECTION_SERVICE: ${{ secrets.URL_SOCIAL_MEDIA_CONNECTION_SERVICE }}

