name: Update VPS Repo with Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  # build-and-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4 # Checkout your code from the repository
  #     - name: Setup Nodejs 20
  #       uses: actions/setup-node@v4 # Install Node.js and npm
  #       with:
  #         node-version: "20" # Replace with your desired Node.js version (if needed)

  #     - name: Install Dependencies autoprefixer
  #       run: npm install autoprefixer

  #     - name: Dependencies and Build Application
  #       working-directory: main-app # Change directory to your application folder
  #       run: npm ci && npm run build # Run build script

  vps-pull-restart:
    runs-on: ubuntu-latest
    # needs: [build-and-test] # This job depends on the successful completion of build-and-deploy
    steps:
      - uses: appleboy/ssh-action@master # Action to connect to VPS via SSH
        with:
          host: ${{ secrets.VPS_IP }} # Replace with your VPS hostname or IP
          username: "root" # Replace with your VPS username
          password: ${{ secrets.VPS_PASSWORD }} # Access password stored as secret
      - name: Connect to VPS (SSH)
        run: | # Conditional script to ensure successful build and handle errors
          cd /home/ubuntu/ris/PublishWhere  # Change directory to deployment location
          git pull origin main             # Pull updates from the main branch
          pm2 restart all                 # Restart the application using pm2
      - name: Disconnect from VPS
        run: exit # Gracefully disconnect from VPS

# All environment variables are stored as secrets in GitHub Secrets
env:
  MONGODB_URL: ${{ secrets.MONGODB_URL }}
  NODE_ENV: "production"
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
  BUCKET_ACCESS_KEY: ${{ secrets.BUCKET_ACCESS_KEY }}
  BUCKET_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_ACCESS_KEY }}
  URL_SOCIAL_MEDIA_CONNECTION_SERVICE: ${{ secrets.URL_SOCIAL_MEDIA_CONNECTION_SERVICE }}
