name: Update VPS Repo with Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: "VPS Prod" # Refer to the environment

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Dependencies and Build Application
        working-directory: main-app
        run: npx @next/codemod built-in-next-font . && npm ci && npm run build
        env:
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          NODE_ENV: "production"
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
          BUCKET_ACCESS_KEY: ${{ secrets.BUCKET_ACCESS_KEY }}
          BUCKET_SECRET_ACCESS_KEY: ${{ secrets.BUCKET_ACCESS_KEY }}
          URL_SOCIAL_MEDIA_CONNECTION_SERVICE: ${{ secrets.URL_SOCIAL_MEDIA_CONNECTION_SERVICE }}

  vps-pull-restart:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    environment: "VPS Prod" # Refer to the environment

    steps:
      - uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: "root"
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            cd /home/ubuntu/ris/PublishWhere
            git pull origin main
            /root/.nvm/versions/node/v20.12.2/bin/pm2 restart all
